# LLM Classifications analysis

In [1]:
import pandas as pd
from typing import Dict, Any
import re
import pandas as pd
import numpy as np

In [2]:
def enrich_program_metadata(df: pd.DataFrame, drop_filename: bool = False) -> pd.DataFrame:
    """
    Parse the 'filename' field and add:
        - program: canonical program family (10 values)
        - opt_level: O0/O1/O2/O3/Os/Ofast/default
        - compiler: gcc or clang

    Parameters
    ----------
    df : DataFrame
        Input dataframe containing column 'filename'.
    drop_filename : bool
        If True, removes the original 'filename' column.

    Returns
    -------
    DataFrame
        Enriched DataFrame with new columns.
    """

    # --------------------------------------------
    # 1) Canonical Program Family Mapping
    # --------------------------------------------
    program_map = {
        "picohttpparser":          "PicoHTTPParser",
        "cjson":                   "cJSON",
        "http_parser":             "Benoitc_HTTP",
        "parse_xml":               "CParserXML",
        "example":                 "CSimpleJSONParser",
        "network_analyzer":        "Network_Packet_Analyzer",
        "elf-parser":              "ELF_Parser",
        "pcap_parser":             "PCAP_Parser",
        "packcc":                  "Packcc",
        "calc":                    "YACC_Calculator",   # calc is also from YACC grammar
    }

    # --------------------------------------------
    # 2) Function to extract canonical program name
    # --------------------------------------------
    def extract_program(fname):
        for prefix, canonical in program_map.items():
            if fname.startswith(prefix):
                return canonical
        return "UNKNOWN"

    # --------------------------------------------
    # 3) Extract optimization level
    # --------------------------------------------
    def extract_opt_level(fname):
        # Order matters: check Ofast before O3, etc
        if "_Ofast" in fname:
            return "Ofast"
        if "_O3" in fname:
            return "O3"
        if "_O2" in fname:
            return "O2"
        if "_O1" in fname:
            return "O1"
        if "_O0" in fname:
            return "O0"
        if "_Os" in fname:
            return "Os"
        return "default"

    # --------------------------------------------
    # 4) Extract compiler
    # --------------------------------------------
    def extract_compiler(fname):
        return "clang" if "_clang" in fname else "gcc"

    # ------------------------------------------------
    # Apply all parsing functions
    # ------------------------------------------------
    df = df.copy()
    df["program"] = df["filename"].apply(extract_program)
    df["opt_level"] = df["filename"].apply(extract_opt_level)
    df["compiler"] = df["filename"].apply(extract_compiler)

    # Remove original filename if requested
    if drop_filename:
        df = df.drop(columns=["filename"])

    return df

In [3]:
def compute_program_recall(df: pd.DataFrame, program_name: str, code_column: str) -> Dict[str, Any]:
    """
    Compute recall and additional statistics for a specific *program* (not filename).

    Parameters
    ----------
    df : pandas.DataFrame
        The entire prediction dataset loaded from the CSV.
    program_name : str
        Canonical name of the program (matches column 'program').

    Returns
    -------
    Dict[str, Any]
        Dictionary with recall and detailed statistics.
    """

    # Filter rows belonging to this program
    prog_df = df[df["program"] == program_name]

    if prog_df.empty:
        raise ValueError(f"No entries found for program '{program_name}'")

    # ----------------------------------------------------------
    # Convert predicted & true labels to numeric, coercing errors
    # non-numeric labels become NaN and will be excluded automatically
    # ----------------------------------------------------------
    true = pd.to_numeric(prog_df["true_label"], errors="coerce")
    pred = pd.to_numeric(prog_df["predicted_label"], errors="coerce")

    # ----------------------------------------------------------
    # Missing code ("" or NaN)
    # ----------------------------------------------------------
    missing_code = ((prog_df[code_column].isna()) |
                      (prog_df[code_column] == "")).sum()

    # ----------------------------------------------------------
    # Recall computation only on valid numeric entries
    # ----------------------------------------------------------
    valid_mask = (~true.isna()) & (~pred.isna())
    true_valid = true[valid_mask]
    pred_valid = pred[valid_mask]

    tp = ((true_valid == 1) & (pred_valid == 1)).sum()
    actual_pos = (true_valid == 1).sum()

    if actual_pos == 0:
        recall = 1.0
    else:
        recall = tp / actual_pos

    # ----------------------------------------------------------
    # Predicted label statistics
    # ----------------------------------------------------------
    num_pred_0 = (pred_valid == 0).sum()
    num_pred_1 = (pred_valid == 1).sum()
    num_pred_unknown = pred.isna().sum()

    # ----------------------------------------------------------
    # Return statistics dictionary
    # ----------------------------------------------------------
    stats = {
        "program_name": program_name,
        "num_entries": len(prog_df),
        "num_valid_predictions": len(pred_valid),
        "num_missing_code": missing_code,

        # Prediction distribution
        "num_pred_0": num_pred_0,
        "num_pred_1": num_pred_1,
        "num_pred_unknown": num_pred_unknown,

        # Recall metrics
        "true_positives": tp,
        "actual_positives": actual_pos,
        "recall": recall,
    }

    return stats

## Mistral

### Decompiled Code LLM Classifications analysis

In [28]:
df = pd.read_csv("../Results/llm_classification_mistral/global_predictions_decompiled_code.csv")
# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 6)

,filename,function_name,address,decompiled_code,predicted_label,true_label
0,parse_xml,sym.deregister_tm_clones,0x401110,long long deregister_tm_clones()\n{\n if (t...,0,0
1,parse_xml,sym.register_tm_clones,0x401140,long long register_tm_clones()\n{\n if (tru...,0,0
2,parse_xml,sym.__do_global_dtors_aux,0x401180,extern char __bss_start;\n\nlong long __do_glo...,0,0
3,parse_xml,sym.frame_dummy,0x4011b0,long long frame_dummy()\n{\n return registe...,0,0
4,parse_xml,sym.skip_whitespace,0x4011cb,long long skip_whitespace(unsigned long a0)\n{...,0,1

In [29]:
# Remove the filename column and add: program, compiler, opt_level
df = enrich_program_metadata(df, drop_filename=True)

# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 8)

,function_name,address,decompiled_code,predicted_label,true_label,program,opt_level,compiler
0,sym.deregister_tm_clones,0x401110,long long deregister_tm_clones()\n{\n if (t...,0,0,CParserXML,default,gcc
1,sym.register_tm_clones,0x401140,long long register_tm_clones()\n{\n if (tru...,0,0,CParserXML,default,gcc
2,sym.__do_global_dtors_aux,0x401180,extern char __bss_start;\n\nlong long __do_glo...,0,0,CParserXML,default,gcc
3,sym.frame_dummy,0x4011b0,long long frame_dummy()\n{\n return registe...,0,0,CParserXML,default,gcc
4,sym.skip_whitespace,0x4011cb,long long skip_whitespace(unsigned long a0)\n{...,0,1,CParserXML,default,gcc

In [30]:
# List of unique programs
programs = df["program"].unique()
programs

array(['CParserXML', 'PicoHTTPParser', 'CSimpleJSONParser', 'cJSON',
       'Benoitc_HTTP', 'YACC_Calculator', 'Network_Packet_Analyzer',
       'ELF_Parser', 'PCAP_Parser', 'Packcc'], dtype=object)

In [31]:
recalls = []                    # Store recall statistics for each program
tot_missing_code = []           # Store total missing code statistics
tot_non_valid_predictions = []  # Store total non-valid predictions statistics

# Compute and print recall statistics for each program
for prog in programs:
    stats = compute_program_recall(df, prog, code_column="decompiled_code")
    print("-------------------------------------------------------------------------------------------------------------")
    print(f"Program: {prog}")
    print(f"  Number of entries: {stats['num_entries']}")
    print(f"  Number of valid predictions: {stats['num_valid_predictions']}")
    print(f"  Number of missing code: {stats['num_missing_code']}")
    print(f"  Predicted label distribution: 0s={stats['num_pred_0']}, 1s={stats['num_pred_1']}, unknown={stats['num_pred_unknown']}")
    print(f"  True Positives: {stats['true_positives']}")
    print(f"  Actual Positives: {stats['actual_positives']}")
    print(f"  Recall: {stats['recall']:.4f}")
    # Accumulate for overall statistics
    recalls.append(stats['recall'])
    tot_missing_code.append(stats['num_missing_code'])
    tot_non_valid_predictions.append(stats['num_entries'] - stats['num_valid_predictions'])

print(f"\n")
print("=============================================================================================================")
overall_recall_mean = np.mean(recalls)
overall_recall_std = np.std(recalls)
print(f"Overall Recall across all programs: {overall_recall_mean:.4f} ± {overall_recall_std:.4f}")
total_missing_code = sum(tot_missing_code)
total_non_valid_predictions = sum(tot_non_valid_predictions)
print(f"Total missing code entries across all programs: {total_missing_code}")
print(f"Total non-valid prediction entries across all programs: {total_non_valid_predictions}")
print(f"Total entries analyzed: {df.shape[0]}")

-------------------------------------------------------------------------------------------------------------
Program: CParserXML
  Number of entries: 362
  Number of valid predictions: 315
  Number of missing code: 45
  Predicted label distribution: 0s=158, 1s=157, unknown=47
  True Positives: 142
  Actual Positives: 185
  Recall: 0.7676
-------------------------------------------------------------------------------------------------------------
Program: PicoHTTPParser
  Number of entries: 760
  Number of valid predictions: 699
  Number of missing code: 58
  Predicted label distribution: 0s=286, 1s=413, unknown=61
  True Positives: 264
  Actual Positives: 323
  Recall: 0.8173
-------------------------------------------------------------------------------------------------------------
Program: CSimpleJSONParser
  Number of entries: 653
  Number of valid predictions: 604
  Number of missing code: 49
  Predicted label distribution: 0s=297, 1s=307, unknown=49
  True Positives: 146
  Actual Positives: 165
  Recall: 0.8848
-------------------------------------------------------------------------------------------------------------
Program: cJSON
  Number of entries: 2293
  Number of valid predictions: 2137
  Number of missing code: 154
  Predicted label distribution: 0s=902, 1s=1235, unknown=156
  True Positives: 136
  Actual Positives: 235
  Recall: 0.5787
-------------------------------------------------------------------------------------------------------------
Program: Benoitc_HTTP
  Number of entries: 421
  Number of valid predictions: 308
  Number of missing code: 112
  Predicted label distribution: 0s=203, 1s=105, unknown=113
  True Positives: 26
  Actual Positives: 58
  Recall: 0.4483
-------------------------------------------------------------------------------------------------------------
Program: YACC_Calculator
  Number of entries: 252
  Number of valid predictions: 247
  Number of missing code: 4
  Predicted label distribution: 0s=110, 1s=137, unknown=5
  True Positives: 19
  Actual Positives: 25
  Recall: 0.7600
-------------------------------------------------------------------------------------------------------------
Program: Network_Packet_Analyzer
  Number of entries: 382
  Number of valid predictions: 354
  Number of missing code: 28
  Predicted label distribution: 0s=145, 1s=209, unknown=28
  True Positives: 56
  Actual Positives: 56
  Recall: 1.0000
-------------------------------------------------------------------------------------------------------------
Program: ELF_Parser
  Number of entries: 679
  Number of valid predictions: 490
  Number of missing code: 186
  Predicted label distribution: 0s=252, 1s=238, unknown=189
  True Positives: 120
  Actual Positives: 166
  Recall: 0.7229
-------------------------------------------------------------------------------------------------------------
Program: PCAP_Parser
  Number of entries: 294
  Number of valid predictions: 266
  Number of missing code: 28
  Predicted label distribution: 0s=177, 1s=89, unknown=28
  True Positives: 25
  Actual Positives: 28
  Recall: 0.8929
-------------------------------------------------------------------------------------------------------------
Program: Packcc
  Number of entries: 1802
  Number of valid predictions: 1581
  Number of missing code: 198
  Predicted label distribution: 0s=863, 1s=718, unknown=221
  True Positives: 346
  Actual Positives: 472
  Recall: 0.7331


=============================================================================================================
Overall Recall across all programs: 0.7606 ± 0.1504
Total missing code entries across all programs: 862
Total non-valid prediction entries across all programs: 897
Total entries analyzed: 7898

### VEX IR LLM Classifications analysis

In [32]:
df = pd.read_csv("../Results/llm_classification_mistral/global_predictions_vex_ir_code.csv")
# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 6)

,filename,function_name,address,vex_ir_code,predicted_label,true_label
0,parse_xml,sym.deregister_tm_clones,0x401110,"------ IMark(0x401110, 5, 0) ------\nPUT(offse...",1,0
1,parse_xml,sym.register_tm_clones,0x401140,"------ IMark(0x401140, 5, 0) ------\n------ IM...",1,0
2,parse_xml,sym.__do_global_dtors_aux,0x401180,"------ IMark(0x401180, 4, 0) ------\nPUT(offse...",1,0
3,parse_xml,sym.frame_dummy,0x4011b0,"------ IMark(0x4011b0, 4, 0) ------\n------ IM...",1,0
4,parse_xml,sym.skip_whitespace,0x4011cb,"------ IMark(0x40120a, 5, 0) ------\nt5 = GET:...",1,1

In [33]:
# Remove the filename column and add: program, compiler, opt_level
df = enrich_program_metadata(df, drop_filename=True)

# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 8)

,function_name,address,vex_ir_code,predicted_label,true_label,program,opt_level,compiler
0,sym.deregister_tm_clones,0x401110,"------ IMark(0x401110, 5, 0) ------\nPUT(offse...",1,0,CParserXML,default,gcc
1,sym.register_tm_clones,0x401140,"------ IMark(0x401140, 5, 0) ------\n------ IM...",1,0,CParserXML,default,gcc
2,sym.__do_global_dtors_aux,0x401180,"------ IMark(0x401180, 4, 0) ------\nPUT(offse...",1,0,CParserXML,default,gcc
3,sym.frame_dummy,0x4011b0,"------ IMark(0x4011b0, 4, 0) ------\n------ IM...",1,0,CParserXML,default,gcc
4,sym.skip_whitespace,0x4011cb,"------ IMark(0x40120a, 5, 0) ------\nt5 = GET:...",1,1,CParserXML,default,gcc

In [34]:
# List of unique programs
programs = df["program"].unique()
programs

array(['CParserXML', 'PicoHTTPParser', 'CSimpleJSONParser', 'cJSON',
       'Benoitc_HTTP', 'YACC_Calculator', 'Network_Packet_Analyzer',
       'ELF_Parser', 'PCAP_Parser', 'Packcc'], dtype=object)

In [35]:
recalls = []                    # Store recall statistics for each program
tot_missing_code = []           # Store total missing code statistics
tot_non_valid_predictions = []  # Store total non-valid predictions statistics

# Compute and print recall statistics for each program
for prog in programs:
    stats = compute_program_recall(df, prog, code_column="vex_ir_code")
    print("-------------------------------------------------------------------------------------------------------------")
    print(f"Program: {prog}")
    print(f"  Number of entries: {stats['num_entries']}")
    print(f"  Number of valid predictions: {stats['num_valid_predictions']}")
    print(f"  Number of missing code: {stats['num_missing_code']}")
    print(f"  Predicted label distribution: 0s={stats['num_pred_0']}, 1s={stats['num_pred_1']}, unknown={stats['num_pred_unknown']}")
    print(f"  True Positives: {stats['true_positives']}")
    print(f"  Actual Positives: {stats['actual_positives']}")
    print(f"  Recall: {stats['recall']:.4f}")
    # Accumulate for overall statistics
    recalls.append(stats['recall'])
    tot_missing_code.append(stats['num_missing_code'])
    tot_non_valid_predictions.append(stats['num_entries'] - stats['num_valid_predictions'])

print(f"\n")
print("=============================================================================================================")
overall_recall_mean = np.mean(recalls)
overall_recall_std = np.std(recalls)
print(f"Overall Recall across all programs: {overall_recall_mean:.4f} ± {overall_recall_std:.4f}")
total_missing_code = sum(tot_missing_code)
total_non_valid_predictions = sum(tot_non_valid_predictions)
print(f"Total missing code entries across all programs: {total_missing_code}")
print(f"Total non-valid prediction entries across all programs: {total_non_valid_predictions}")
print(f"Total entries analyzed: {df.shape[0]}")

-------------------------------------------------------------------------------------------------------------
Program: CParserXML
  Number of entries: 362
  Number of valid predictions: 330
  Number of missing code: 0
  Predicted label distribution: 0s=69, 1s=261, unknown=32
  True Positives: 116
  Actual Positives: 173
  Recall: 0.6705
-------------------------------------------------------------------------------------------------------------
Program: PicoHTTPParser
  Number of entries: 760
  Number of valid predictions: 684
  Number of missing code: 0
  Predicted label distribution: 0s=289, 1s=395, unknown=76
  True Positives: 127
  Actual Positives: 295
  Recall: 0.4305
-------------------------------------------------------------------------------------------------------------
Program: CSimpleJSONParser
  Number of entries: 653
  Number of valid predictions: 589
  Number of missing code: 0
  Predicted label distribution: 0s=210, 1s=379, unknown=64
  True Positives: 65
  Actual Positives: 153
  Recall: 0.4248
-------------------------------------------------------------------------------------------------------------
Program: cJSON
  Number of entries: 2293
  Number of valid predictions: 2144
  Number of missing code: 0
  Predicted label distribution: 0s=643, 1s=1501, unknown=149
  True Positives: 92
  Actual Positives: 225
  Recall: 0.4089
-------------------------------------------------------------------------------------------------------------
Program: Benoitc_HTTP
  Number of entries: 421
  Number of valid predictions: 395
  Number of missing code: 0
  Predicted label distribution: 0s=92, 1s=303, unknown=26
  True Positives: 34
  Actual Positives: 82
  Recall: 0.4146
-------------------------------------------------------------------------------------------------------------
Program: YACC_Calculator
  Number of entries: 252
  Number of valid predictions: 232
  Number of missing code: 0
  Predicted label distribution: 0s=79, 1s=153, unknown=20
  True Positives: 14
  Actual Positives: 25
  Recall: 0.5600
-------------------------------------------------------------------------------------------------------------
Program: Network_Packet_Analyzer
  Number of entries: 382
  Number of valid predictions: 360
  Number of missing code: 0
  Predicted label distribution: 0s=117, 1s=243, unknown=22
  True Positives: 34
  Actual Positives: 52
  Recall: 0.6538
-------------------------------------------------------------------------------------------------------------
Program: ELF_Parser
  Number of entries: 679
  Number of valid predictions: 581
  Number of missing code: 0
  Predicted label distribution: 0s=283, 1s=298, unknown=98
  True Positives: 81
  Actual Positives: 190
  Recall: 0.4263
-------------------------------------------------------------------------------------------------------------
Program: PCAP_Parser
  Number of entries: 294
  Number of valid predictions: 283
  Number of missing code: 0
  Predicted label distribution: 0s=58, 1s=225, unknown=11
  True Positives: 8
  Actual Positives: 22
  Recall: 0.3636
-------------------------------------------------------------------------------------------------------------
Program: Packcc
  Number of entries: 1802
  Number of valid predictions: 1592
  Number of missing code: 0
  Predicted label distribution: 0s=660, 1s=932, unknown=210
  True Positives: 210
  Actual Positives: 475
  Recall: 0.4421


=============================================================================================================
Overall Recall across all programs: 0.4795 ± 0.1028
Total missing code entries across all programs: 0
Total non-valid prediction entries across all programs: 708
Total entries analyzed: 7898

### Assembly Code LLM Classifications analysis

In [42]:
df = pd.read_csv("../Results/llm_classification_mistral/global_predictions_assembly_code.csv")
# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 6)

,filename,function_name,address,assembly_code,predicted_label,true_label
0,parse_xml,sym.deregister_tm_clones,0x401110,"0x401110:\tmov\teax, 0x405058\n0x401115:\tcmp\...",0,0
1,parse_xml,sym.register_tm_clones,0x401140,"0x401140:\tmov\tesi, 0x405058\n0x401145:\tsub\...",1,0
2,parse_xml,sym.__do_global_dtors_aux,0x401180,0x401180:\tendbr64\t\n0x401184:\tcmp\tbyte ptr...,1,0
3,parse_xml,sym.frame_dummy,0x4011b0,0x4011b0:\tendbr64\t\n0x4011b4:\tjmp\t0x401140,0,0
4,parse_xml,sym.skip_whitespace,0x4011cb,"0x40120a:\tadd\tqword ptr [rbp - 8], 1\n0x4012...",1,1

In [43]:
# Remove the filename column and add: program, compiler, opt_level
df = enrich_program_metadata(df, drop_filename=True)

# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 8)

,function_name,address,assembly_code,predicted_label,true_label,program,opt_level,compiler
0,sym.deregister_tm_clones,0x401110,"0x401110:\tmov\teax, 0x405058\n0x401115:\tcmp\...",0,0,CParserXML,default,gcc
1,sym.register_tm_clones,0x401140,"0x401140:\tmov\tesi, 0x405058\n0x401145:\tsub\...",1,0,CParserXML,default,gcc
2,sym.__do_global_dtors_aux,0x401180,0x401180:\tendbr64\t\n0x401184:\tcmp\tbyte ptr...,1,0,CParserXML,default,gcc
3,sym.frame_dummy,0x4011b0,0x4011b0:\tendbr64\t\n0x4011b4:\tjmp\t0x401140,0,0,CParserXML,default,gcc
4,sym.skip_whitespace,0x4011cb,"0x40120a:\tadd\tqword ptr [rbp - 8], 1\n0x4012...",1,1,CParserXML,default,gcc

In [44]:
# List of unique programs
programs = df["program"].unique()
programs

array(['CParserXML', 'PicoHTTPParser', 'CSimpleJSONParser', 'cJSON',
       'Benoitc_HTTP', 'YACC_Calculator', 'Network_Packet_Analyzer',
       'ELF_Parser', 'PCAP_Parser', 'Packcc'], dtype=object)

In [45]:
recalls = []                    # Store recall statistics for each program
tot_missing_code = []           # Store total missing code statistics
tot_non_valid_predictions = []  # Store total non-valid predictions statistics

# Compute and print recall statistics for each program
for prog in programs:
    stats = compute_program_recall(df, prog, code_column="assembly_code")
    print("-------------------------------------------------------------------------------------------------------------")
    print(f"Program: {prog}")
    print(f"  Number of entries: {stats['num_entries']}")
    print(f"  Number of valid predictions: {stats['num_valid_predictions']}")
    print(f"  Number of missing code: {stats['num_missing_code']}")
    print(f"  Predicted label distribution: 0s={stats['num_pred_0']}, 1s={stats['num_pred_1']}, unknown={stats['num_pred_unknown']}")
    print(f"  True Positives: {stats['true_positives']}")
    print(f"  Actual Positives: {stats['actual_positives']}")
    print(f"  Recall: {stats['recall']:.4f}")
    # Accumulate for overall statistics
    recalls.append(stats['recall'])
    tot_missing_code.append(stats['num_missing_code'])
    tot_non_valid_predictions.append(stats['num_entries'] - stats['num_valid_predictions'])

print(f"\n")
print("=============================================================================================================")
overall_recall_mean = np.mean(recalls)
overall_recall_std = np.std(recalls)
print(f"Overall Recall across all programs: {overall_recall_mean:.4f} ± {overall_recall_std:.4f}")
total_missing_code = sum(tot_missing_code)
total_non_valid_predictions = sum(tot_non_valid_predictions)
print(f"Total missing code entries across all programs: {total_missing_code}")
print(f"Total non-valid prediction entries across all programs: {total_non_valid_predictions}")
print(f"Total entries analyzed: {df.shape[0]}")

-------------------------------------------------------------------------------------------------------------
Program: CParserXML
  Number of entries: 362
  Number of valid predictions: 351
  Number of missing code: 0
  Predicted label distribution: 0s=92, 1s=259, unknown=11
  True Positives: 148
  Actual Positives: 193
  Recall: 0.7668
-------------------------------------------------------------------------------------------------------------
Program: PicoHTTPParser
  Number of entries: 760
  Number of valid predictions: 735
  Number of missing code: 0
  Predicted label distribution: 0s=133, 1s=602, unknown=25
  True Positives: 226
  Actual Positives: 310
  Recall: 0.7290
-------------------------------------------------------------------------------------------------------------
Program: CSimpleJSONParser
  Number of entries: 653
  Number of valid predictions: 647
  Number of missing code: 0
  Predicted label distribution: 0s=74, 1s=573, unknown=6
  True Positives: 168
  Actual Positives: 180
  Recall: 0.9333
-------------------------------------------------------------------------------------------------------------
Program: cJSON
  Number of entries: 2293
  Number of valid predictions: 2271
  Number of missing code: 0
  Predicted label distribution: 0s=129, 1s=2142, unknown=22
  True Positives: 206
  Actual Positives: 246
  Recall: 0.8374
-------------------------------------------------------------------------------------------------------------
Program: Benoitc_HTTP
  Number of entries: 421
  Number of valid predictions: 415
  Number of missing code: 0
  Predicted label distribution: 0s=91, 1s=324, unknown=6
  True Positives: 60
  Actual Positives: 90
  Recall: 0.6667
-------------------------------------------------------------------------------------------------------------
Program: YACC_Calculator
  Number of entries: 252
  Number of valid predictions: 246
  Number of missing code: 0
  Predicted label distribution: 0s=42, 1s=204, unknown=6
  True Positives: 7
  Actual Positives: 23
  Recall: 0.3043
-------------------------------------------------------------------------------------------------------------
Program: Network_Packet_Analyzer
  Number of entries: 382
  Number of valid predictions: 382
  Number of missing code: 0
  Predicted label distribution: 0s=47, 1s=335, unknown=0
  True Positives: 56
  Actual Positives: 56
  Recall: 1.0000
-------------------------------------------------------------------------------------------------------------
Program: ELF_Parser
  Number of entries: 679
  Number of valid predictions: 621
  Number of missing code: 0
  Predicted label distribution: 0s=153, 1s=468, unknown=58
  True Positives: 108
  Actual Positives: 186
  Recall: 0.5806
-------------------------------------------------------------------------------------------------------------
Program: PCAP_Parser
  Number of entries: 294
  Number of valid predictions: 294
  Number of missing code: 0
  Predicted label distribution: 0s=50, 1s=244, unknown=0
  True Positives: 28
  Actual Positives: 28
  Recall: 1.0000
-------------------------------------------------------------------------------------------------------------
Program: Packcc
  Number of entries: 1802
  Number of valid predictions: 1718
  Number of missing code: 13
  Predicted label distribution: 0s=374, 1s=1344, unknown=84
  True Positives: 391
  Actual Positives: 522
  Recall: 0.7490


=============================================================================================================
Overall Recall across all programs: 0.7567 ± 0.2002
Total missing code entries across all programs: 13
Total non-valid prediction entries across all programs: 218
Total entries analyzed: 7898

## Codellama:34b

### Decompiled Code LLM Classifications analysis

In [4]:
df = pd.read_csv("../Results/llm_classification_codellama_34b/global_predictions_decompiled_code.csv")
# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 6)

,filename,function_name,address,decompiled_code,predicted_label,true_label
0,parse_xml,sym.deregister_tm_clones,0x401110,long long deregister_tm_clones()\n{\n if (t...,0,0
1,parse_xml,sym.register_tm_clones,0x401140,long long register_tm_clones()\n{\n if (tru...,1,0
2,parse_xml,sym.__do_global_dtors_aux,0x401180,extern char __bss_start;\n\nlong long __do_glo...,0,0
3,parse_xml,sym.frame_dummy,0x4011b0,long long frame_dummy()\n{\n return registe...,0,0
4,parse_xml,sym.skip_whitespace,0x4011cb,long long skip_whitespace(unsigned long a0)\n{...,1,1

In [5]:
# Remove the filename column and add: program, compiler, opt_level
df = enrich_program_metadata(df, drop_filename=True)

# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 8)

,function_name,address,decompiled_code,predicted_label,true_label,program,opt_level,compiler
0,sym.deregister_tm_clones,0x401110,long long deregister_tm_clones()\n{\n if (t...,0,0,CParserXML,default,gcc
1,sym.register_tm_clones,0x401140,long long register_tm_clones()\n{\n if (tru...,1,0,CParserXML,default,gcc
2,sym.__do_global_dtors_aux,0x401180,extern char __bss_start;\n\nlong long __do_glo...,0,0,CParserXML,default,gcc
3,sym.frame_dummy,0x4011b0,long long frame_dummy()\n{\n return registe...,0,0,CParserXML,default,gcc
4,sym.skip_whitespace,0x4011cb,long long skip_whitespace(unsigned long a0)\n{...,1,1,CParserXML,default,gcc

In [6]:
# List of unique programs
programs = df["program"].unique()
programs

array(['CParserXML', 'PicoHTTPParser', 'CSimpleJSONParser', 'cJSON',
       'Benoitc_HTTP', 'YACC_Calculator', 'Network_Packet_Analyzer',
       'ELF_Parser', 'PCAP_Parser', 'Packcc'], dtype=object)

In [7]:
recalls = []                    # Store recall statistics for each program
tot_missing_code = []           # Store total missing code statistics
tot_non_valid_predictions = []  # Store total non-valid predictions statistics

# Compute and print recall statistics for each program
for prog in programs:
    stats = compute_program_recall(df, prog, code_column="decompiled_code")
    print("-------------------------------------------------------------------------------------------------------------")
    print(f"Program: {prog}")
    print(f"  Number of entries: {stats['num_entries']}")
    print(f"  Number of valid predictions: {stats['num_valid_predictions']}")
    print(f"  Number of missing code: {stats['num_missing_code']}")
    print(f"  Predicted label distribution: 0s={stats['num_pred_0']}, 1s={stats['num_pred_1']}, unknown={stats['num_pred_unknown']}")
    print(f"  True Positives: {stats['true_positives']}")
    print(f"  Actual Positives: {stats['actual_positives']}")
    print(f"  Recall: {stats['recall']:.4f}")
    # Accumulate for overall statistics
    recalls.append(stats['recall'])
    tot_missing_code.append(stats['num_missing_code'])
    tot_non_valid_predictions.append(stats['num_entries'] - stats['num_valid_predictions'])

print(f"\n")
print("=============================================================================================================")
overall_recall_mean = np.mean(recalls)
overall_recall_std = np.std(recalls)
print(f"Overall Recall across all programs: {overall_recall_mean:.4f} ± {overall_recall_std:.4f}")
total_missing_code = sum(tot_missing_code)
total_non_valid_predictions = sum(tot_non_valid_predictions)
print(f"Total missing code entries across all programs: {total_missing_code}")
print(f"Total non-valid prediction entries across all programs: {total_non_valid_predictions}")
print(f"Total entries analyzed: {df.shape[0]}")

-------------------------------------------------------------------------------------------------------------
Program: CParserXML
  Number of entries: 362
  Number of valid predictions: 288
  Number of missing code: 45
  Predicted label distribution: 0s=147, 1s=141, unknown=74
  True Positives: 90
  Actual Positives: 160
  Recall: 0.5625
-------------------------------------------------------------------------------------------------------------
Program: PicoHTTPParser
  Number of entries: 760
  Number of valid predictions: 600
  Number of missing code: 59
  Predicted label distribution: 0s=251, 1s=349, unknown=160
  True Positives: 174
  Actual Positives: 261
  Recall: 0.6667
-------------------------------------------------------------------------------------------------------------
Program: CSimpleJSONParser
  Number of entries: 653
  Number of valid predictions: 548
  Number of missing code: 49
  Predicted label distribution: 0s=247, 1s=301, unknown=105
  True Positives: 99
  Actual Positives: 149
  Recall: 0.6644
-------------------------------------------------------------------------------------------------------------
Program: cJSON
  Number of entries: 2293
  Number of valid predictions: 1884
  Number of missing code: 154
  Predicted label distribution: 0s=877, 1s=1007, unknown=409
  True Positives: 108
  Actual Positives: 207
  Recall: 0.5217
-------------------------------------------------------------------------------------------------------------
Program: Benoitc_HTTP
  Number of entries: 421
  Number of valid predictions: 286
  Number of missing code: 112
  Predicted label distribution: 0s=141, 1s=145, unknown=135
  True Positives: 20
  Actual Positives: 51
  Recall: 0.3922
-------------------------------------------------------------------------------------------------------------
Program: YACC_Calculator
  Number of entries: 252
  Number of valid predictions: 221
  Number of missing code: 4
  Predicted label distribution: 0s=97, 1s=124, unknown=31
  True Positives: 11
  Actual Positives: 24
  Recall: 0.4583
-------------------------------------------------------------------------------------------------------------
Program: Network_Packet_Analyzer
  Number of entries: 382
  Number of valid predictions: 328
  Number of missing code: 28
  Predicted label distribution: 0s=172, 1s=156, unknown=54
  True Positives: 32
  Actual Positives: 53
  Recall: 0.6038
-------------------------------------------------------------------------------------------------------------
Program: ELF_Parser
  Number of entries: 679
  Number of valid predictions: 393
  Number of missing code: 186
  Predicted label distribution: 0s=167, 1s=226, unknown=286
  True Positives: 65
  Actual Positives: 113
  Recall: 0.5752
-------------------------------------------------------------------------------------------------------------
Program: PCAP_Parser
  Number of entries: 294
  Number of valid predictions: 245
  Number of missing code: 28
  Predicted label distribution: 0s=128, 1s=117, unknown=49
  True Positives: 15
  Actual Positives: 25
  Recall: 0.6000
-------------------------------------------------------------------------------------------------------------
Program: Packcc
  Number of entries: 1802
  Number of valid predictions: 1369
  Number of missing code: 198
  Predicted label distribution: 0s=615, 1s=754, unknown=433
  True Positives: 271
  Actual Positives: 411
  Recall: 0.6594


=============================================================================================================
Overall Recall across all programs: 0.5704 ± 0.0865
Total missing code entries across all programs: 863
Total non-valid prediction entries across all programs: 1736
Total entries analyzed: 7898

### VEX IR LLM Classifications analysis

In [4]:
df = pd.read_csv("../Results/llm_classification_codellama_34b/global_predictions_vex_ir_code.csv")
# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 6)

,filename,function_name,address,vex_ir_code,predicted_label,true_label
0,parse_xml,sym.deregister_tm_clones,0x401110,"------ IMark(0x401110, 5, 0) ------\nPUT(offse...",1,0
1,parse_xml,sym.register_tm_clones,0x401140,"------ IMark(0x401140, 5, 0) ------\n------ IM...",0,0
2,parse_xml,sym.__do_global_dtors_aux,0x401180,"------ IMark(0x401180, 4, 0) ------\nPUT(offse...",unknown,0
3,parse_xml,sym.frame_dummy,0x4011b0,"------ IMark(0x4011b0, 4, 0) ------\n------ IM...",0,0
4,parse_xml,sym.skip_whitespace,0x4011cb,"------ IMark(0x40120a, 5, 0) ------\nt5 = GET:...",unknown,1

In [5]:
# Remove the filename column and add: program, compiler, opt_level
df = enrich_program_metadata(df, drop_filename=True)

# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 8)

,function_name,address,vex_ir_code,predicted_label,true_label,program,opt_level,compiler
0,sym.deregister_tm_clones,0x401110,"------ IMark(0x401110, 5, 0) ------\nPUT(offse...",1,0,CParserXML,default,gcc
1,sym.register_tm_clones,0x401140,"------ IMark(0x401140, 5, 0) ------\n------ IM...",0,0,CParserXML,default,gcc
2,sym.__do_global_dtors_aux,0x401180,"------ IMark(0x401180, 4, 0) ------\nPUT(offse...",unknown,0,CParserXML,default,gcc
3,sym.frame_dummy,0x4011b0,"------ IMark(0x4011b0, 4, 0) ------\n------ IM...",0,0,CParserXML,default,gcc
4,sym.skip_whitespace,0x4011cb,"------ IMark(0x40120a, 5, 0) ------\nt5 = GET:...",unknown,1,CParserXML,default,gcc

In [6]:
# List of unique programs
programs = df["program"].unique()
programs

array(['CParserXML', 'PicoHTTPParser', 'CSimpleJSONParser', 'cJSON',
       'Benoitc_HTTP', 'YACC_Calculator', 'Network_Packet_Analyzer',
       'ELF_Parser', 'PCAP_Parser', 'Packcc'], dtype=object)

In [7]:
recalls = []                    # Store recall statistics for each program
tot_missing_code = []           # Store total missing code statistics
tot_non_valid_predictions = []  # Store total non-valid predictions statistics

# Compute and print recall statistics for each program
for prog in programs:
    stats = compute_program_recall(df, prog, code_column="vex_ir_code")
    print("-------------------------------------------------------------------------------------------------------------")
    print(f"Program: {prog}")
    print(f"  Number of entries: {stats['num_entries']}")
    print(f"  Number of valid predictions: {stats['num_valid_predictions']}")
    print(f"  Number of missing code: {stats['num_missing_code']}")
    print(f"  Predicted label distribution: 0s={stats['num_pred_0']}, 1s={stats['num_pred_1']}, unknown={stats['num_pred_unknown']}")
    print(f"  True Positives: {stats['true_positives']}")
    print(f"  Actual Positives: {stats['actual_positives']}")
    print(f"  Recall: {stats['recall']:.4f}")
    # Accumulate for overall statistics
    recalls.append(stats['recall'])
    tot_missing_code.append(stats['num_missing_code'])
    tot_non_valid_predictions.append(stats['num_entries'] - stats['num_valid_predictions'])

print(f"\n")
print("=============================================================================================================")
overall_recall_mean = np.mean(recalls)
overall_recall_std = np.std(recalls)
print(f"Overall Recall across all programs: {overall_recall_mean:.4f} ± {overall_recall_std:.4f}")
total_missing_code = sum(tot_missing_code)
total_non_valid_predictions = sum(tot_non_valid_predictions)
print(f"Total missing code entries across all programs: {total_missing_code}")
print(f"Total non-valid prediction entries across all programs: {total_non_valid_predictions}")
print(f"Total entries analyzed: {df.shape[0]}")

-------------------------------------------------------------------------------------------------------------
Program: CParserXML
  Number of entries: 362
  Number of valid predictions: 234
  Number of missing code: 0
  Predicted label distribution: 0s=102, 1s=132, unknown=128
  True Positives: 64
  Actual Positives: 116
  Recall: 0.5517
-------------------------------------------------------------------------------------------------------------
Program: PicoHTTPParser
  Number of entries: 760
  Number of valid predictions: 439
  Number of missing code: 0
  Predicted label distribution: 0s=199, 1s=240, unknown=321
  True Positives: 82
  Actual Positives: 164
  Recall: 0.5000
-------------------------------------------------------------------------------------------------------------
Program: CSimpleJSONParser
  Number of entries: 653
  Number of valid predictions: 423
  Number of missing code: 0
  Predicted label distribution: 0s=196, 1s=227, unknown=230
  True Positives: 51
  Actual Positives: 96
  Recall: 0.5312
-------------------------------------------------------------------------------------------------------------
Program: cJSON
  Number of entries: 2293
  Number of valid predictions: 1496
  Number of missing code: 0
  Predicted label distribution: 0s=617, 1s=879, unknown=797
  True Positives: 79
  Actual Positives: 154
  Recall: 0.5130
-------------------------------------------------------------------------------------------------------------
Program: Benoitc_HTTP
  Number of entries: 421
  Number of valid predictions: 271
  Number of missing code: 0
  Predicted label distribution: 0s=109, 1s=162, unknown=150
  True Positives: 23
  Actual Positives: 43
  Recall: 0.5349
-------------------------------------------------------------------------------------------------------------
Program: YACC_Calculator
  Number of entries: 252
  Number of valid predictions: 143
  Number of missing code: 0
  Predicted label distribution: 0s=67, 1s=76, unknown=109
  True Positives: 7
  Actual Positives: 18
  Recall: 0.3889
-------------------------------------------------------------------------------------------------------------
Program: Network_Packet_Analyzer
  Number of entries: 382
  Number of valid predictions: 253
  Number of missing code: 0
  Predicted label distribution: 0s=112, 1s=141, unknown=129
  True Positives: 18
  Actual Positives: 32
  Recall: 0.5625
-------------------------------------------------------------------------------------------------------------
Program: ELF_Parser
  Number of entries: 679
  Number of valid predictions: 373
  Number of missing code: 0
  Predicted label distribution: 0s=195, 1s=178, unknown=306
  True Positives: 50
  Actual Positives: 117
  Recall: 0.4274
-------------------------------------------------------------------------------------------------------------
Program: PCAP_Parser
  Number of entries: 294
  Number of valid predictions: 215
  Number of missing code: 0
  Predicted label distribution: 0s=92, 1s=123, unknown=79
  True Positives: 10
  Actual Positives: 14
  Recall: 0.7143
-------------------------------------------------------------------------------------------------------------
Program: Packcc
  Number of entries: 1802
  Number of valid predictions: 1034
  Number of missing code: 0
  Predicted label distribution: 0s=461, 1s=573, unknown=768
  True Positives: 150
  Actual Positives: 282
  Recall: 0.5319


=============================================================================================================
Overall Recall across all programs: 0.5256 ± 0.0818
Total missing code entries across all programs: 0
Total non-valid prediction entries across all programs: 3017
Total entries analyzed: 7898

### Assembly Code LLM Classifications analysis

In [46]:
df = pd.read_csv("../Results/llm_classification_codellama_34b/global_predictions_assembly_code.csv")
# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 6)

,filename,function_name,address,assembly_code,predicted_label,true_label
0,parse_xml,sym.deregister_tm_clones,0x401110,"0x401110:\tmov\teax, 0x405058\n0x401115:\tcmp\...",0,0
1,parse_xml,sym.register_tm_clones,0x401140,"0x401140:\tmov\tesi, 0x405058\n0x401145:\tsub\...",0,0
2,parse_xml,sym.__do_global_dtors_aux,0x401180,0x401180:\tendbr64\t\n0x401184:\tcmp\tbyte ptr...,0,0
3,parse_xml,sym.frame_dummy,0x4011b0,0x4011b0:\tendbr64\t\n0x4011b4:\tjmp\t0x401140,0,0
4,parse_xml,sym.skip_whitespace,0x4011cb,"0x40120a:\tadd\tqword ptr [rbp - 8], 1\n0x4012...",0,1

In [47]:
# Remove the filename column and add: program, compiler, opt_level
df = enrich_program_metadata(df, drop_filename=True)

# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 8)

,function_name,address,assembly_code,predicted_label,true_label,program,opt_level,compiler
0,sym.deregister_tm_clones,0x401110,"0x401110:\tmov\teax, 0x405058\n0x401115:\tcmp\...",0,0,CParserXML,default,gcc
1,sym.register_tm_clones,0x401140,"0x401140:\tmov\tesi, 0x405058\n0x401145:\tsub\...",0,0,CParserXML,default,gcc
2,sym.__do_global_dtors_aux,0x401180,0x401180:\tendbr64\t\n0x401184:\tcmp\tbyte ptr...,0,0,CParserXML,default,gcc
3,sym.frame_dummy,0x4011b0,0x4011b0:\tendbr64\t\n0x4011b4:\tjmp\t0x401140,0,0,CParserXML,default,gcc
4,sym.skip_whitespace,0x4011cb,"0x40120a:\tadd\tqword ptr [rbp - 8], 1\n0x4012...",0,1,CParserXML,default,gcc

In [48]:
# List of unique programs
programs = df["program"].unique()
programs

array(['CParserXML', 'PicoHTTPParser', 'CSimpleJSONParser', 'cJSON',
       'Benoitc_HTTP', 'YACC_Calculator', 'Network_Packet_Analyzer',
       'ELF_Parser', 'PCAP_Parser', 'Packcc'], dtype=object)

In [49]:
recalls = []                    # Store recall statistics for each program
tot_missing_code = []           # Store total missing code statistics
tot_non_valid_predictions = []  # Store total non-valid predictions statistics

# Compute and print recall statistics for each program
for prog in programs:
    stats = compute_program_recall(df, prog, code_column="assembly_code")
    print("-------------------------------------------------------------------------------------------------------------")
    print(f"Program: {prog}")
    print(f"  Number of entries: {stats['num_entries']}")
    print(f"  Number of valid predictions: {stats['num_valid_predictions']}")
    print(f"  Number of missing code: {stats['num_missing_code']}")
    print(f"  Predicted label distribution: 0s={stats['num_pred_0']}, 1s={stats['num_pred_1']}, unknown={stats['num_pred_unknown']}")
    print(f"  True Positives: {stats['true_positives']}")
    print(f"  Actual Positives: {stats['actual_positives']}")
    print(f"  Recall: {stats['recall']:.4f}")
    # Accumulate for overall statistics
    recalls.append(stats['recall'])
    tot_missing_code.append(stats['num_missing_code'])
    tot_non_valid_predictions.append(stats['num_entries'] - stats['num_valid_predictions'])

print(f"\n")
print("=============================================================================================================")
overall_recall_mean = np.mean(recalls)
overall_recall_std = np.std(recalls)
print(f"Overall Recall across all programs: {overall_recall_mean:.4f} ± {overall_recall_std:.4f}")
total_missing_code = sum(tot_missing_code)
total_non_valid_predictions = sum(tot_non_valid_predictions)
print(f"Total missing code entries across all programs: {total_missing_code}")
print(f"Total non-valid prediction entries across all programs: {total_non_valid_predictions}")
print(f"Total entries analyzed: {df.shape[0]}")

-------------------------------------------------------------------------------------------------------------
Program: CParserXML
  Number of entries: 362
  Number of valid predictions: 283
  Number of missing code: 0
  Predicted label distribution: 0s=150, 1s=133, unknown=79
  True Positives: 75
  Actual Positives: 135
  Recall: 0.5556
-------------------------------------------------------------------------------------------------------------
Program: PicoHTTPParser
  Number of entries: 760
  Number of valid predictions: 562
  Number of missing code: 0
  Predicted label distribution: 0s=271, 1s=291, unknown=198
  True Positives: 111
  Actual Positives: 220
  Recall: 0.5045
-------------------------------------------------------------------------------------------------------------
Program: CSimpleJSONParser
  Number of entries: 653
  Number of valid predictions: 532
  Number of missing code: 0
  Predicted label distribution: 0s=218, 1s=314, unknown=121
  True Positives: 89
  Actual Positives: 134
  Recall: 0.6642
-------------------------------------------------------------------------------------------------------------
Program: cJSON
  Number of entries: 2293
  Number of valid predictions: 1923
  Number of missing code: 0
  Predicted label distribution: 0s=865, 1s=1058, unknown=370
  True Positives: 96
  Actual Positives: 179
  Recall: 0.5363
-------------------------------------------------------------------------------------------------------------
Program: Benoitc_HTTP
  Number of entries: 421
  Number of valid predictions: 339
  Number of missing code: 0
  Predicted label distribution: 0s=194, 1s=145, unknown=82
  True Positives: 25
  Actual Positives: 52
  Recall: 0.4808
-------------------------------------------------------------------------------------------------------------
Program: YACC_Calculator
  Number of entries: 252
  Number of valid predictions: 220
  Number of missing code: 0
  Predicted label distribution: 0s=107, 1s=113, unknown=32
  True Positives: 7
  Actual Positives: 24
  Recall: 0.2917
-------------------------------------------------------------------------------------------------------------
Program: Network_Packet_Analyzer
  Number of entries: 382
  Number of valid predictions: 329
  Number of missing code: 0
  Predicted label distribution: 0s=138, 1s=191, unknown=53
  True Positives: 30
  Actual Positives: 50
  Recall: 0.6000
-------------------------------------------------------------------------------------------------------------
Program: ELF_Parser
  Number of entries: 679
  Number of valid predictions: 497
  Number of missing code: 0
  Predicted label distribution: 0s=249, 1s=248, unknown=182
  True Positives: 68
  Actual Positives: 142
  Recall: 0.4789
-------------------------------------------------------------------------------------------------------------
Program: PCAP_Parser
  Number of entries: 294
  Number of valid predictions: 261
  Number of missing code: 0
  Predicted label distribution: 0s=123, 1s=138, unknown=33
  True Positives: 16
  Actual Positives: 23
  Recall: 0.6957
-------------------------------------------------------------------------------------------------------------
Program: Packcc
  Number of entries: 1802
  Number of valid predictions: 1355
  Number of missing code: 13
  Predicted label distribution: 0s=574, 1s=781, unknown=447
  True Positives: 228
  Actual Positives: 382
  Recall: 0.5969


=============================================================================================================
Overall Recall across all programs: 0.5404 ± 0.1081
Total missing code entries across all programs: 13
Total non-valid prediction entries across all programs: 1597
Total entries analyzed: 7898

## Qwen3-Coder:30b

### Decompiled Code LLM Classifications analysis

In [8]:
df = pd.read_csv("../Results/llm_classification_qwen3_coder_30b/global_predictions_decompiled_code.csv")
# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 6)

,filename,function_name,address,decompiled_code,predicted_label,true_label
0,parse_xml,sym.deregister_tm_clones,0x401110,long long deregister_tm_clones()\n{\n if (t...,0,0
1,parse_xml,sym.register_tm_clones,0x401140,long long register_tm_clones()\n{\n if (tru...,0,0
2,parse_xml,sym.__do_global_dtors_aux,0x401180,extern char __bss_start;\n\nlong long __do_glo...,0,0
3,parse_xml,sym.frame_dummy,0x4011b0,long long frame_dummy()\n{\n return registe...,0,0
4,parse_xml,sym.skip_whitespace,0x4011cb,long long skip_whitespace(unsigned long a0)\n{...,0,1

In [9]:
# Remove the filename column and add: program, compiler, opt_level
df = enrich_program_metadata(df, drop_filename=True)

# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 8)

,function_name,address,decompiled_code,predicted_label,true_label,program,opt_level,compiler
0,sym.deregister_tm_clones,0x401110,long long deregister_tm_clones()\n{\n if (t...,0,0,CParserXML,default,gcc
1,sym.register_tm_clones,0x401140,long long register_tm_clones()\n{\n if (tru...,0,0,CParserXML,default,gcc
2,sym.__do_global_dtors_aux,0x401180,extern char __bss_start;\n\nlong long __do_glo...,0,0,CParserXML,default,gcc
3,sym.frame_dummy,0x4011b0,long long frame_dummy()\n{\n return registe...,0,0,CParserXML,default,gcc
4,sym.skip_whitespace,0x4011cb,long long skip_whitespace(unsigned long a0)\n{...,0,1,CParserXML,default,gcc

In [10]:
# List of unique programs
programs = df["program"].unique()
programs

array(['CParserXML', 'PicoHTTPParser', 'CSimpleJSONParser', 'cJSON',
       'Benoitc_HTTP', 'YACC_Calculator', 'Network_Packet_Analyzer',
       'ELF_Parser', 'PCAP_Parser', 'Packcc'], dtype=object)

In [11]:
recalls = []                    # Store recall statistics for each program
tot_missing_code = []           # Store total missing code statistics
tot_non_valid_predictions = []  # Store total non-valid predictions statistics

# Compute and print recall statistics for each program
for prog in programs:
    stats = compute_program_recall(df, prog, code_column="decompiled_code")
    print("-------------------------------------------------------------------------------------------------------------")
    print(f"Program: {prog}")
    print(f"  Number of entries: {stats['num_entries']}")
    print(f"  Number of valid predictions: {stats['num_valid_predictions']}")
    print(f"  Number of missing code: {stats['num_missing_code']}")
    print(f"  Predicted label distribution: 0s={stats['num_pred_0']}, 1s={stats['num_pred_1']}, unknown={stats['num_pred_unknown']}")
    print(f"  True Positives: {stats['true_positives']}")
    print(f"  Actual Positives: {stats['actual_positives']}")
    print(f"  Recall: {stats['recall']:.4f}")
    # Accumulate for overall statistics
    recalls.append(stats['recall'])
    tot_missing_code.append(stats['num_missing_code'])
    tot_non_valid_predictions.append(stats['num_entries'] - stats['num_valid_predictions'])

print(f"\n")
print("=============================================================================================================")
overall_recall_mean = np.mean(recalls)
overall_recall_std = np.std(recalls)
print(f"Overall Recall across all programs: {overall_recall_mean:.4f} ± {overall_recall_std:.4f}")
total_missing_code = sum(tot_missing_code)
total_non_valid_predictions = sum(tot_non_valid_predictions)
print(f"Total missing code entries across all programs: {total_missing_code}")
print(f"Total non-valid prediction entries across all programs: {total_non_valid_predictions}")
print(f"Total entries analyzed: {df.shape[0]}")

-------------------------------------------------------------------------------------------------------------
Program: CParserXML
  Number of entries: 362
  Number of valid predictions: 315
  Number of missing code: 45
  Predicted label distribution: 0s=224, 1s=91, unknown=47
  True Positives: 91
  Actual Positives: 185
  Recall: 0.4919
-------------------------------------------------------------------------------------------------------------
Program: PicoHTTPParser
  Number of entries: 760
  Number of valid predictions: 692
  Number of missing code: 58
  Predicted label distribution: 0s=378, 1s=314, unknown=68
  True Positives: 216
  Actual Positives: 316
  Recall: 0.6835
-------------------------------------------------------------------------------------------------------------
Program: CSimpleJSONParser
  Number of entries: 653
  Number of valid predictions: 604
  Number of missing code: 49
  Predicted label distribution: 0s=388, 1s=216, unknown=49
  True Positives: 133
  Actual Positives: 165
  Recall: 0.8061
-------------------------------------------------------------------------------------------------------------
Program: cJSON
  Number of entries: 2293
  Number of valid predictions: 2139
  Number of missing code: 154
  Predicted label distribution: 0s=1905, 1s=234, unknown=154
  True Positives: 129
  Actual Positives: 237
  Recall: 0.5443
-------------------------------------------------------------------------------------------------------------
Program: Benoitc_HTTP
  Number of entries: 421
  Number of valid predictions: 309
  Number of missing code: 112
  Predicted label distribution: 0s=290, 1s=19, unknown=112
  True Positives: 17
  Actual Positives: 59
  Recall: 0.2881
-------------------------------------------------------------------------------------------------------------
Program: YACC_Calculator
  Number of entries: 252
  Number of valid predictions: 248
  Number of missing code: 4
  Predicted label distribution: 0s=126, 1s=122, unknown=4
  True Positives: 12
  Actual Positives: 25
  Recall: 0.4800
-------------------------------------------------------------------------------------------------------------
Program: Network_Packet_Analyzer
  Number of entries: 382
  Number of valid predictions: 354
  Number of missing code: 28
  Predicted label distribution: 0s=245, 1s=109, unknown=28
  True Positives: 51
  Actual Positives: 56
  Recall: 0.9107
-------------------------------------------------------------------------------------------------------------
Program: ELF_Parser
  Number of entries: 679
  Number of valid predictions: 493
  Number of missing code: 186
  Predicted label distribution: 0s=409, 1s=84, unknown=186
  True Positives: 41
  Actual Positives: 167
  Recall: 0.2455
-------------------------------------------------------------------------------------------------------------
Program: PCAP_Parser
  Number of entries: 294
  Number of valid predictions: 266
  Number of missing code: 28
  Predicted label distribution: 0s=198, 1s=68, unknown=28
  True Positives: 24
  Actual Positives: 28
  Recall: 0.8571
-------------------------------------------------------------------------------------------------------------
Program: Packcc
  Number of entries: 1802
  Number of valid predictions: 1597
  Number of missing code: 197
  Predicted label distribution: 0s=1183, 1s=414, unknown=205
  True Positives: 269
  Actual Positives: 481
  Recall: 0.5593


=============================================================================================================
Overall Recall across all programs: 0.5867 ± 0.2154
Total missing code entries across all programs: 861
Total non-valid prediction entries across all programs: 881
Total entries analyzed: 7898

### VEX IR LLM Classifications analysis

In [4]:
df = pd.read_csv("../Results/llm_classification_qwen3_coder_30b/global_predictions_vex_ir_code.csv")
# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 6)

,filename,function_name,address,vex_ir_code,predicted_label,true_label
0,parse_xml,sym.deregister_tm_clones,0x401110,"------ IMark(0x401110, 5, 0) ------\nPUT(offse...",1,0
1,parse_xml,sym.register_tm_clones,0x401140,"------ IMark(0x401140, 5, 0) ------\n------ IM...",1,0
2,parse_xml,sym.__do_global_dtors_aux,0x401180,"------ IMark(0x401180, 4, 0) ------\nPUT(offse...",1,0
3,parse_xml,sym.frame_dummy,0x4011b0,"------ IMark(0x4011b0, 4, 0) ------\n------ IM...",0,0
4,parse_xml,sym.skip_whitespace,0x4011cb,"------ IMark(0x40120a, 5, 0) ------\nt5 = GET:...",1,1

In [5]:
# Remove the filename column and add: program, compiler, opt_level
df = enrich_program_metadata(df, drop_filename=True)

# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 8)

,function_name,address,vex_ir_code,predicted_label,true_label,program,opt_level,compiler
0,sym.deregister_tm_clones,0x401110,"------ IMark(0x401110, 5, 0) ------\nPUT(offse...",1,0,CParserXML,default,gcc
1,sym.register_tm_clones,0x401140,"------ IMark(0x401140, 5, 0) ------\n------ IM...",1,0,CParserXML,default,gcc
2,sym.__do_global_dtors_aux,0x401180,"------ IMark(0x401180, 4, 0) ------\nPUT(offse...",1,0,CParserXML,default,gcc
3,sym.frame_dummy,0x4011b0,"------ IMark(0x4011b0, 4, 0) ------\n------ IM...",0,0,CParserXML,default,gcc
4,sym.skip_whitespace,0x4011cb,"------ IMark(0x40120a, 5, 0) ------\nt5 = GET:...",1,1,CParserXML,default,gcc

In [6]:
# List of unique programs
programs = df["program"].unique()
programs

array(['CParserXML', 'PicoHTTPParser', 'CSimpleJSONParser', 'cJSON',
       'Benoitc_HTTP', 'YACC_Calculator', 'Network_Packet_Analyzer',
       'ELF_Parser', 'PCAP_Parser', 'Packcc'], dtype=object)

In [7]:
recalls = []                    # Store recall statistics for each program
tot_missing_code = []           # Store total missing code statistics
tot_non_valid_predictions = []  # Store total non-valid predictions statistics

# Compute and print recall statistics for each program
for prog in programs:
    stats = compute_program_recall(df, prog, code_column="vex_ir_code")
    print("-------------------------------------------------------------------------------------------------------------")
    print(f"Program: {prog}")
    print(f"  Number of entries: {stats['num_entries']}")
    print(f"  Number of valid predictions: {stats['num_valid_predictions']}")
    print(f"  Number of missing code: {stats['num_missing_code']}")
    print(f"  Predicted label distribution: 0s={stats['num_pred_0']}, 1s={stats['num_pred_1']}, unknown={stats['num_pred_unknown']}")
    print(f"  True Positives: {stats['true_positives']}")
    print(f"  Actual Positives: {stats['actual_positives']}")
    print(f"  Recall: {stats['recall']:.4f}")
    # Accumulate for overall statistics
    recalls.append(stats['recall'])
    tot_missing_code.append(stats['num_missing_code'])
    tot_non_valid_predictions.append(stats['num_entries'] - stats['num_valid_predictions'])

print(f"\n")
print("=============================================================================================================")
overall_recall_mean = np.mean(recalls)
overall_recall_std = np.std(recalls)
print(f"Overall Recall across all programs: {overall_recall_mean:.4f} ± {overall_recall_std:.4f}")
total_missing_code = sum(tot_missing_code)
total_non_valid_predictions = sum(tot_non_valid_predictions)
print(f"Total missing code entries across all programs: {total_missing_code}")
print(f"Total non-valid prediction entries across all programs: {total_non_valid_predictions}")
print(f"Total entries analyzed: {df.shape[0]}")

-------------------------------------------------------------------------------------------------------------
Program: CParserXML
  Number of entries: 362
  Number of valid predictions: 361
  Number of missing code: 0
  Predicted label distribution: 0s=158, 1s=203, unknown=1
  True Positives: 84
  Actual Positives: 203
  Recall: 0.4138
-------------------------------------------------------------------------------------------------------------
Program: PicoHTTPParser
  Number of entries: 760
  Number of valid predictions: 734
  Number of missing code: 0
  Predicted label distribution: 0s=526, 1s=208, unknown=26
  True Positives: 19
  Actual Positives: 320
  Recall: 0.0594
-------------------------------------------------------------------------------------------------------------
Program: CSimpleJSONParser
  Number of entries: 653
  Number of valid predictions: 653
  Number of missing code: 0
  Predicted label distribution: 0s=393, 1s=260, unknown=0
  True Positives: 20
  Actual Positives: 184
  Recall: 0.1087
-------------------------------------------------------------------------------------------------------------
Program: cJSON
  Number of entries: 2293
  Number of valid predictions: 2280
  Number of missing code: 0
  Predicted label distribution: 0s=1052, 1s=1228, unknown=13
  True Positives: 40
  Actual Positives: 257
  Recall: 0.1556
-------------------------------------------------------------------------------------------------------------
Program: Benoitc_HTTP
  Number of entries: 421
  Number of valid predictions: 421
  Number of missing code: 0
  Predicted label distribution: 0s=200, 1s=221, unknown=0
  True Positives: 2
  Actual Positives: 95
  Recall: 0.0211
-------------------------------------------------------------------------------------------------------------
Program: YACC_Calculator
  Number of entries: 252
  Number of valid predictions: 252
  Number of missing code: 0
  Predicted label distribution: 0s=141, 1s=111, unknown=0
  True Positives: 6
  Actual Positives: 29
  Recall: 0.2069
-------------------------------------------------------------------------------------------------------------
Program: Network_Packet_Analyzer
  Number of entries: 382
  Number of valid predictions: 382
  Number of missing code: 0
  Predicted label distribution: 0s=183, 1s=199, unknown=0
  True Positives: 35
  Actual Positives: 56
  Recall: 0.6250
-------------------------------------------------------------------------------------------------------------
Program: ELF_Parser
  Number of entries: 679
  Number of valid predictions: 678
  Number of missing code: 0
  Predicted label distribution: 0s=546, 1s=132, unknown=1
  True Positives: 34
  Actual Positives: 229
  Recall: 0.1485
-------------------------------------------------------------------------------------------------------------
Program: PCAP_Parser
  Number of entries: 294
  Number of valid predictions: 290
  Number of missing code: 0
  Predicted label distribution: 0s=133, 1s=157, unknown=4
  True Positives: 1
  Actual Positives: 24
  Recall: 0.0417
-------------------------------------------------------------------------------------------------------------
Program: Packcc
  Number of entries: 1802
  Number of valid predictions: 1776
  Number of missing code: 0
  Predicted label distribution: 0s=1198, 1s=578, unknown=26
  True Positives: 80
  Actual Positives: 553
  Recall: 0.1447


=============================================================================================================
Overall Recall across all programs: 0.1925 ± 0.1785
Total missing code entries across all programs: 0
Total non-valid prediction entries across all programs: 71
Total entries analyzed: 7898

### Assembly Code LLM Classifications analysis

In [4]:
df = pd.read_csv("../Results/llm_classification_qwen3_coder_30b/global_predictions_assembly_code.csv")
# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 6)

,filename,function_name,address,assembly_code,predicted_label,true_label
0,parse_xml,sym.deregister_tm_clones,0x401110,"0x401110:\tmov\teax, 0x405058\n0x401115:\tcmp\...",0,0
1,parse_xml,sym.register_tm_clones,0x401140,"0x401140:\tmov\tesi, 0x405058\n0x401145:\tsub\...",0,0
2,parse_xml,sym.__do_global_dtors_aux,0x401180,0x401180:\tendbr64\t\n0x401184:\tcmp\tbyte ptr...,0,0
3,parse_xml,sym.frame_dummy,0x4011b0,0x4011b0:\tendbr64\t\n0x4011b4:\tjmp\t0x401140,0,0
4,parse_xml,sym.skip_whitespace,0x4011cb,"0x40120a:\tadd\tqword ptr [rbp - 8], 1\n0x4012...",0,1

In [5]:
# Remove the filename column and add: program, compiler, opt_level
df = enrich_program_metadata(df, drop_filename=True)

# Shape of the dataframe
print(f"df.shape: {df.shape}")
# Display first few rows
df.head()

df.shape: (7898, 8)

,function_name,address,assembly_code,predicted_label,true_label,program,opt_level,compiler
0,sym.deregister_tm_clones,0x401110,"0x401110:\tmov\teax, 0x405058\n0x401115:\tcmp\...",0,0,CParserXML,default,gcc
1,sym.register_tm_clones,0x401140,"0x401140:\tmov\tesi, 0x405058\n0x401145:\tsub\...",0,0,CParserXML,default,gcc
2,sym.__do_global_dtors_aux,0x401180,0x401180:\tendbr64\t\n0x401184:\tcmp\tbyte ptr...,0,0,CParserXML,default,gcc
3,sym.frame_dummy,0x4011b0,0x4011b0:\tendbr64\t\n0x4011b4:\tjmp\t0x401140,0,0,CParserXML,default,gcc
4,sym.skip_whitespace,0x4011cb,"0x40120a:\tadd\tqword ptr [rbp - 8], 1\n0x4012...",0,1,CParserXML,default,gcc

In [6]:
# List of unique programs
programs = df["program"].unique()
programs

array(['CParserXML', 'PicoHTTPParser', 'CSimpleJSONParser', 'cJSON',
       'Benoitc_HTTP', 'YACC_Calculator', 'Network_Packet_Analyzer',
       'ELF_Parser', 'PCAP_Parser', 'Packcc'], dtype=object)

In [7]:
recalls = []                    # Store recall statistics for each program
tot_missing_code = []           # Store total missing code statistics
tot_non_valid_predictions = []  # Store total non-valid predictions statistics

# Compute and print recall statistics for each program
for prog in programs:
    stats = compute_program_recall(df, prog, code_column="assembly_code")
    print("-------------------------------------------------------------------------------------------------------------")
    print(f"Program: {prog}")
    print(f"  Number of entries: {stats['num_entries']}")
    print(f"  Number of valid predictions: {stats['num_valid_predictions']}")
    print(f"  Number of missing code: {stats['num_missing_code']}")
    print(f"  Predicted label distribution: 0s={stats['num_pred_0']}, 1s={stats['num_pred_1']}, unknown={stats['num_pred_unknown']}")
    print(f"  True Positives: {stats['true_positives']}")
    print(f"  Actual Positives: {stats['actual_positives']}")
    print(f"  Recall: {stats['recall']:.4f}")
    # Accumulate for overall statistics
    recalls.append(stats['recall'])
    tot_missing_code.append(stats['num_missing_code'])
    tot_non_valid_predictions.append(stats['num_entries'] - stats['num_valid_predictions'])

print(f"\n")
print("=============================================================================================================")
overall_recall_mean = np.mean(recalls)
overall_recall_std = np.std(recalls)
print(f"Overall Recall across all programs: {overall_recall_mean:.4f} ± {overall_recall_std:.4f}")
total_missing_code = sum(tot_missing_code)
total_non_valid_predictions = sum(tot_non_valid_predictions)
print(f"Total missing code entries across all programs: {total_missing_code}")
print(f"Total non-valid prediction entries across all programs: {total_non_valid_predictions}")
print(f"Total entries analyzed: {df.shape[0]}")

-------------------------------------------------------------------------------------------------------------
Program: CParserXML
  Number of entries: 362
  Number of valid predictions: 356
  Number of missing code: 0
  Predicted label distribution: 0s=236, 1s=120, unknown=6
  True Positives: 104
  Actual Positives: 198
  Recall: 0.5253
-------------------------------------------------------------------------------------------------------------
Program: PicoHTTPParser
  Number of entries: 760
  Number of valid predictions: 760
  Number of missing code: 0
  Predicted label distribution: 0s=299, 1s=461, unknown=0
  True Positives: 203
  Actual Positives: 334
  Recall: 0.6078
-------------------------------------------------------------------------------------------------------------
Program: CSimpleJSONParser
  Number of entries: 653
  Number of valid predictions: 653
  Number of missing code: 0
  Predicted label distribution: 0s=243, 1s=410, unknown=0
  True Positives: 157
  Actual Positives: 184
  Recall: 0.8533
-------------------------------------------------------------------------------------------------------------
Program: cJSON
  Number of entries: 2293
  Number of valid predictions: 2293
  Number of missing code: 0
  Predicted label distribution: 0s=1147, 1s=1146, unknown=0
  True Positives: 156
  Actual Positives: 260
  Recall: 0.6000
-------------------------------------------------------------------------------------------------------------
Program: Benoitc_HTTP
  Number of entries: 421
  Number of valid predictions: 421
  Number of missing code: 0
  Predicted label distribution: 0s=324, 1s=97, unknown=0
  True Positives: 44
  Actual Positives: 95
  Recall: 0.4632
-------------------------------------------------------------------------------------------------------------
Program: YACC_Calculator
  Number of entries: 252
  Number of valid predictions: 252
  Number of missing code: 0
  Predicted label distribution: 0s=122, 1s=130, unknown=0
  True Positives: 0
  Actual Positives: 29
  Recall: 0.0000
-------------------------------------------------------------------------------------------------------------
Program: Network_Packet_Analyzer
  Number of entries: 382
  Number of valid predictions: 382
  Number of missing code: 0
  Predicted label distribution: 0s=128, 1s=254, unknown=0
  True Positives: 52
  Actual Positives: 56
  Recall: 0.9286
-------------------------------------------------------------------------------------------------------------
Program: ELF_Parser
  Number of entries: 679
  Number of valid predictions: 672
  Number of missing code: 0
  Predicted label distribution: 0s=337, 1s=335, unknown=7
  True Positives: 74
  Actual Positives: 224
  Recall: 0.3304
-------------------------------------------------------------------------------------------------------------
Program: PCAP_Parser
  Number of entries: 294
  Number of valid predictions: 294
  Number of missing code: 0
  Predicted label distribution: 0s=160, 1s=134, unknown=0
  True Positives: 28
  Actual Positives: 28
  Recall: 1.0000
-------------------------------------------------------------------------------------------------------------
Program: Packcc
  Number of entries: 1802
  Number of valid predictions: 1779
  Number of missing code: 13
  Predicted label distribution: 0s=760, 1s=1019, unknown=23
  True Positives: 325
  Actual Positives: 550
  Recall: 0.5909


=============================================================================================================
Overall Recall across all programs: 0.5899 ± 0.2808
Total missing code entries across all programs: 13
Total non-valid prediction entries across all programs: 36
Total entries analyzed: 7898